/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import view.TelaLoging;
/**
 *
 * @author danie
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
        setTitle("Sistema de vendas de mangas");
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jToolBar1 = new javax.swing.JToolBar();
        wam_JbtnUsuario = new javax.swing.JButton();
        wam_jBtnVendedor = new javax.swing.JButton();
        wam_jBtnVenda = new javax.swing.JButton();
        wam_jBtnProduto = new javax.swing.JButton();
        wam_jBtnCliente = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMniUsuario = new javax.swing.JMenuItem();
        jMniVendedor = new javax.swing.JMenuItem();
        jMniCliente = new javax.swing.JMenuItem();
        jMniProdutos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMniSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMniVendas = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenConsultVendas = new javax.swing.JMenuItem();
        jMenuConsultClientes = new javax.swing.JMenuItem();
        jMenuConsutProdutos = new javax.swing.JMenuItem();
        jMenuConsultUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        wam_JbtnUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-anime-32.png"))); // NOI18N
        wam_JbtnUsuario.setFocusable(false);
        wam_JbtnUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        wam_JbtnUsuario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        wam_JbtnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wam_JbtnUsuarioActionPerformed(evt);
            }
        });
        jToolBar1.add(wam_JbtnUsuario);

        wam_jBtnVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-kuromi-32.png"))); // NOI18N
        wam_jBtnVendedor.setFocusable(false);
        wam_jBtnVendedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        wam_jBtnVendedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        wam_jBtnVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wam_jBtnVendedorActionPerformed(evt);
            }
        });
        jToolBar1.add(wam_jBtnVendedor);

        wam_jBtnVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-dinheiro-32.png"))); // NOI18N
        wam_jBtnVenda.setFocusable(false);
        wam_jBtnVenda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        wam_jBtnVenda.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        wam_jBtnVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wam_jBtnVendaActionPerformed(evt);
            }
        });
        jToolBar1.add(wam_jBtnVenda);

        wam_jBtnProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-manga-32.png"))); // NOI18N
        wam_jBtnProduto.setFocusable(false);
        wam_jBtnProduto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        wam_jBtnProduto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        wam_jBtnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wam_jBtnProdutoActionPerformed(evt);
            }
        });
        jToolBar1.add(wam_jBtnProduto);

        wam_jBtnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-anime-48.png"))); // NOI18N
        wam_jBtnCliente.setFocusable(false);
        wam_jBtnCliente.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        wam_jBtnCliente.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        wam_jBtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wam_jBtnClienteActionPerformed(evt);
            }
        });
        jToolBar1.add(wam_jBtnCliente);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-skyrim-32.png"))); // NOI18N
        jMenu1.setText("Cadastro");

        jMniUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-anime-32.png"))); // NOI18N
        jMniUsuario.setText("Usuário");
        jMniUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniUsuarioActionPerformed(evt);
            }
        });
        jMenu1.add(jMniUsuario);

        jMniVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-kuromi-32.png"))); // NOI18N
        jMniVendedor.setText("Vendedor");
        jMniVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniVendedorActionPerformed(evt);
            }
        });
        jMenu1.add(jMniVendedor);

        jMniCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-anime-48.png"))); // NOI18N
        jMniCliente.setText("Cliente");
        jMniCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniClienteActionPerformed(evt);
            }
        });
        jMenu1.add(jMniCliente);

        jMniProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-manga-32.png"))); // NOI18N
        jMniProdutos.setText("Produtos");
        jMniProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniProdutosActionPerformed(evt);
            }
        });
        jMenu1.add(jMniProdutos);
        jMenu1.add(jSeparator1);

        jMniSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-espada-32.png"))); // NOI18N
        jMniSair.setText("Sair");
        jMniSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniSairActionPerformed(evt);
            }
        });
        jMenu1.add(jMniSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-exoesqueleto-32.png"))); // NOI18N
        jMenu2.setText("Movimento");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMniVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-dinheiro-32.png"))); // NOI18N
        jMniVendas.setText("Vendas");
        jMniVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMniVendasActionPerformed(evt);
            }
        });
        jMenu2.add(jMniVendas);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-manga-32.png"))); // NOI18N
        jMenuItem1.setText("Produtos_Vendas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-espada-32.png"))); // NOI18N
        jMenu3.setText("Consultas");

        jMenConsultVendas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenConsultVendas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-dinheiro-32.png"))); // NOI18N
        jMenConsultVendas.setText("Vendas");
        jMenConsultVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenConsultVendasActionPerformed(evt);
            }
        });
        jMenu3.add(jMenConsultVendas);

        jMenuConsultClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuConsultClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-anime-48.png"))); // NOI18N
        jMenuConsultClientes.setText("Clientes");
        jMenuConsultClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultClientesActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuConsultClientes);

        jMenuConsutProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuConsutProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-manga-32.png"))); // NOI18N
        jMenuConsutProdutos.setText("Produtos");
        jMenuConsutProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsutProdutosActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuConsutProdutos);

        jMenuConsultUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuConsultUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-anime-32.png"))); // NOI18N
        jMenuConsultUsuario.setText("Usuario");
        jMenuConsultUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuConsultUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuConsultUsuario);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMniProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniProdutosActionPerformed
        // TODO add your handling code here:
        JDlgProdutos jDlgProdutos = new JDlgProdutos(null, true);
        jDlgProdutos.setVisible(true);
    }//GEN-LAST:event_jMniProdutosActionPerformed

    private void jMniUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniUsuarioActionPerformed
        // TODO add your handling code here:
        JDlgUsuarios jDlgUsuarios= new JDlgUsuarios(null, true);
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMniUsuarioActionPerformed

    private void jMniClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniClienteActionPerformed
        // TODO add your handling code here:
        JDlgClientes jDlgClientes = new JDlgClientes(null, true);
        jDlgClientes.setVisible(true);
    }//GEN-LAST:event_jMniClienteActionPerformed

    private void jMniVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniVendedorActionPerformed
        // TODO add your handling code here:
        JDlgVendedor jDlgVendedor = new JDlgVendedor(null, true);
        jDlgVendedor.setVisible(true);
    }//GEN-LAST:event_jMniVendedorActionPerformed

    private void jMniVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniVendasActionPerformed
        // TODO add your handling code here:
       JDlgVendas jDlgVendas = new JDlgVendas(null, true);
       jDlgVendas.setVisible(true);
    }//GEN-LAST:event_jMniVendasActionPerformed

    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        //JDlgProduto_Venda jDlgProduto_Venda = new JDlgProduto_Venda(null, true);
        //jDlgProduto_Venda.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMniSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMniSairActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_jMniSairActionPerformed

    private void jMenuConsultClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultClientesActionPerformed
        // TODO add your handling code here:
        JDlgConsultaClientes jDlgConsultaClientes = new JDlgConsultaClientes(null, true);
        jDlgConsultaClientes.setVisible(true);
    }//GEN-LAST:event_jMenuConsultClientesActionPerformed

    private void jMenuConsutProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsutProdutosActionPerformed
        // TODO add your handling code here:
        JDlgConsultaProdutos jDlgConsultaProdutos = new JDlgConsultaProdutos(null, true);
        jDlgConsultaProdutos.setVisible(true);
    }//GEN-LAST:event_jMenuConsutProdutosActionPerformed

    private void wam_JbtnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wam_JbtnUsuarioActionPerformed
        // TODO add your handling code here:
        jMniUsuarioActionPerformed(null);
    }//GEN-LAST:event_wam_JbtnUsuarioActionPerformed

    private void wam_jBtnVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wam_jBtnVendedorActionPerformed
        // TODO add your handling code here:
        jMniVendedorActionPerformed(null);
    }//GEN-LAST:event_wam_jBtnVendedorActionPerformed

    private void wam_jBtnVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wam_jBtnVendaActionPerformed
        // TODO add your handling code here:
        jMniVendasActionPerformed(null);
    }//GEN-LAST:event_wam_jBtnVendaActionPerformed

    private void wam_jBtnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wam_jBtnProdutoActionPerformed
        // TODO add your handling code here:
        jMenuConsutProdutosActionPerformed(null);
    }//GEN-LAST:event_wam_jBtnProdutoActionPerformed

    private void wam_jBtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wam_jBtnClienteActionPerformed
        // TODO add your handling code here:
        jMenuConsultClientesActionPerformed(null);
    }//GEN-LAST:event_wam_jBtnClienteActionPerformed

    private void jMenConsultVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenConsultVendasActionPerformed
        // TODO add your handling code here:
        JDlgConsultaVenda jDlgConsultaVendas = new JDlgConsultaVenda(null, true);
        jDlgConsultaVendas.setVisible(true);
    }//GEN-LAST:event_jMenConsultVendasActionPerformed

    private void jMenuConsultUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuConsultUsuarioActionPerformed
        // TODO add your handling code here:
        JDlgConsultaUsuario jDlgConsultaUsuario= new JDlgConsultaUsuario(null, true);
        jDlgConsultaUsuario.setVisible(true);
    }//GEN-LAST:event_jMenuConsultUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenConsultVendas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuConsultClientes;
    private javax.swing.JMenuItem jMenuConsultUsuario;
    private javax.swing.JMenuItem jMenuConsutProdutos;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMniCliente;
    private javax.swing.JMenuItem jMniProdutos;
    private javax.swing.JMenuItem jMniSair;
    private javax.swing.JMenuItem jMniUsuario;
    private javax.swing.JMenuItem jMniVendas;
    private javax.swing.JMenuItem jMniVendedor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton wam_JbtnUsuario;
    private javax.swing.JButton wam_jBtnCliente;
    private javax.swing.JButton wam_jBtnProduto;
    private javax.swing.JButton wam_jBtnVenda;
    private javax.swing.JButton wam_jBtnVendedor;
    // End of variables declaration//GEN-END:variables
}
