package bean;
// Generated 11/10/2025 18:12:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * WamCliente generated by hbm2java
 */
@Entity
@Table(name="wam_cliente"
    ,catalog="db_willian_martinez"
    , uniqueConstraints = @UniqueConstraint(columnNames="wam_cpf") 
)
public class WamCliente  implements java.io.Serializable {


     private Integer idCliente;
     private String wamNome;
     private String wamRg;
     private String wamCpf;
     private String wamSexo;
     private Date wamDataNascimento;
     private String wamTelefone;
     private String wamCelular;
     private String wamBairro;
     private String wamCidade;
     private String wamEstado;
     private String wamAtivo;
     private String wamEmail;
     private String wamEmpresa;
     private String wamCep;
    

    public WamCliente() {
    }

	
    public WamCliente(String wamNome, String wamCpf) {
        this.wamNome = wamNome;
        this.wamCpf = wamCpf;
    }
    public WamCliente(String wamNome, String wamRg, String wamCpf, String wamSexo, Date wamDataNascimento, String wamTelefone, String wamCelular, String wamBairro, String wamCidade, String wamEstado, String wamAtivo, String wamEmail, String wamEmpresa, String wamCep) {
       this.wamNome = wamNome;
       this.wamRg = wamRg;
       this.wamCpf = wamCpf;
       this.wamSexo = wamSexo;
       this.wamDataNascimento = wamDataNascimento;
       this.wamTelefone = wamTelefone;
       this.wamCelular = wamCelular;
       this.wamBairro = wamBairro;
       this.wamCidade = wamCidade;
       this.wamEstado = wamEstado;
       this.wamAtivo = wamAtivo;
       this.wamEmail = wamEmail;
       this.wamEmpresa = wamEmpresa;
       this.wamCep = wamCep;
       
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCliente", unique=true, nullable=false)
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }

    
    @Column(name="wam_nome", nullable=false, length=100)
    public String getWamNome() {
        return this.wamNome;
    }
    
    public void setWamNome(String wamNome) {
        this.wamNome = wamNome;
    }

    
    @Column(name="wam_rg", length=20)
    public String getWamRg() {
        return this.wamRg;
    }
    
    public void setWamRg(String wamRg) {
        this.wamRg = wamRg;
    }

    
    @Column(name="wam_cpf", unique=true, nullable=false, length=19)
    public String getWamCpf() {
        return this.wamCpf;
    }
    
    public void setWamCpf(String wamCpf) {
        this.wamCpf = wamCpf;
    }

    
    @Column(name="wam_sexo", length=2)
    public String getWamSexo() {
        return this.wamSexo;
    }
    
    public void setWamSexo(String wamSexo) {
        this.wamSexo = wamSexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="wam_dataNascimento", length=10)
    public Date getWamDataNascimento() {
        return this.wamDataNascimento;
    }
    
    public void setWamDataNascimento(Date wamDataNascimento) {
        this.wamDataNascimento = wamDataNascimento;
    }

    
    @Column(name="wam_telefone", length=20)
    public String getWamTelefone() {
        return this.wamTelefone;
    }
    
    public void setWamTelefone(String wamTelefone) {
        this.wamTelefone = wamTelefone;
    }

    
    @Column(name="wam_celular", length=20)
    public String getWamCelular() {
        return this.wamCelular;
    }
    
    public void setWamCelular(String wamCelular) {
        this.wamCelular = wamCelular;
    }

    
    @Column(name="wam_bairro", length=50)
    public String getWamBairro() {
        return this.wamBairro;
    }
    
    public void setWamBairro(String wamBairro) {
        this.wamBairro = wamBairro;
    }

    
    @Column(name="wam_cidade", length=50)
    public String getWamCidade() {
        return this.wamCidade;
    }
    
    public void setWamCidade(String wamCidade) {
        this.wamCidade = wamCidade;
    }

    
    @Column(name="wam_estado", length=2)
    public String getWamEstado() {
        return this.wamEstado;
    }
    
    public void setWamEstado(String wamEstado) {
        this.wamEstado = wamEstado;
    }

    
    @Column(name="wam_ativo")
    public String getWamAtivo() {
        return this.wamAtivo;
    }
    
    public void setWamAtivo(String wamAtivo) {
        this.wamAtivo = wamAtivo;
    }

    
    @Column(name="wam_email", length=100)
    public String getWamEmail() {
        return this.wamEmail;
    }
    
    public void setWamEmail(String wamEmail) {
        this.wamEmail = wamEmail;
    }

    
    @Column(name="wam_empresa", length=100)
    public String getWamEmpresa() {
        return this.wamEmpresa;
    }
    
    public void setWamEmpresa(String wamEmpresa) {
        this.wamEmpresa = wamEmpresa;
    }

    
    @Column(name="wam_cep", length=20)
    public String getWamCep() {
        return this.wamCep;
    }
    
    public void setWamCep(String wamCep) {
        this.wamCep = wamCep;
    }






}


