package bean;
// Generated 11/10/2025 18:12:54 by Hibernate Tools 4.3.1



import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * WamProduto generated by hbm2java
 */
@Entity
@Table(name="wam_Produto"
    ,catalog="db_willian_martinez"
)
public class WamProduto  implements java.io.Serializable {


     private Integer idProduto;
     private String wamNome;
     private Double wamValor;
     private String wamAutor;
     private String wamDescricao;
     private String wamEditora;
     private Boolean wamVolume;
     //private Set wamVendaProdutos = new HashSet(0);

    public WamProduto() {
    }

	
    public WamProduto(String wamNome, Double wamValor) {
        this.wamNome = wamNome;
        this.wamValor = wamValor;
    }
    public WamProduto(String wamNome, Double wamValor, String wamAutor, String wamDescricao, String wamEditora, Boolean wamVolume, Set wamVendaProdutos) {
       this.wamNome = wamNome;
       this.wamValor = wamValor;
       this.wamAutor = wamAutor;
       this.wamDescricao = wamDescricao;
       this.wamEditora = wamEditora;
       this.wamVolume = wamVolume;
       //this.wamVendaProdutos = wamVendaProdutos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idProduto", unique=true, nullable=false)
    public Integer getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Integer idProduto) {
        this.idProduto = idProduto;
    }

    
    @Column(name="wam_nome", nullable=false, length=100)
    public String getWamNome() {
        return this.wamNome;
    }
    
    public void setWamNome(String wamNome) {
        this.wamNome = wamNome;
    }

    
    @Column(name="wam_valor", nullable=false, precision=10)
    public Double getWamValor() {
        return this.wamValor;
    }
    
    public void setWamValor(Double wamValor) {
        this.wamValor = wamValor;
    }

    
    @Column(name="wam_autor", length=100)
    public String getWamAutor() {
        return this.wamAutor;
    }
    
    public void setWamAutor(String wamAutor) {
        this.wamAutor = wamAutor;
    }

    
    @Column(name="wam_descricao", length=65535)
    public String getWamDescricao() {
        return this.wamDescricao;
    }
    
    public void setWamDescricao(String wamDescricao) {
        this.wamDescricao = wamDescricao;
    }

    
    @Column(name="wam_editora", length=100)
    public String getWamEditora() {
        return this.wamEditora;
    }
    
    public void setWamEditora(String wamEditora) {
        this.wamEditora = wamEditora;
    }

    
    @Column(name="wam_volume")
    public Boolean getWamVolume() {
        return this.wamVolume;
    }
    
    public void setWamVolume(Boolean wamVolume) {
        this.wamVolume = wamVolume;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="wamProduto")
//    public Set getWamVendaProdutos() {
//        return this.wamVendaProdutos;
//    }
//    
//    public void setWamVendaProdutos(Set wamVendaProdutos) {
//        this.wamVendaProdutos = wamVendaProdutos;
//    }




}


