package bean;
// Generated 10/10/2025 15:04:07 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * WamUsuario generated by hbm2java
 */
@Entity
@Table(name="wam_usuario"
    ,catalog="db_willian_martinez"
    , uniqueConstraints = @UniqueConstraint(columnNames="wam_cpf") 
)
public class WamUsuario  implements java.io.Serializable {


     private Integer wamIdUsuario;
     private String wamNome;
     private String wamApelido;
     private String wamCpf;
     private Date wamDataNascimento;
     private Integer wamNivel;
     private Boolean wamAtivo;

    public WamUsuario() {
    }

	
    public WamUsuario(String wamNome, String wamCpf) {
        this.wamNome = wamNome;
        this.wamCpf = wamCpf;
    }
    public WamUsuario(String wamNome, String wamApelido, String wamCpf, Date wamDataNascimento, Integer wamNivel, Boolean wamAtivo) {
       this.wamNome = wamNome;
       this.wamApelido = wamApelido;
       this.wamCpf = wamCpf;
       this.wamDataNascimento = wamDataNascimento;
       this.wamNivel = wamNivel;
       this.wamAtivo = wamAtivo;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="wam_idUsuario", unique=true, nullable=false)
    public Integer getWamIdUsuario() {
        return this.wamIdUsuario;
    }
    
    public void setWamIdUsuario(Integer wamIdUsuario) {
        this.wamIdUsuario = wamIdUsuario;
    }

    
    @Column(name="wam_nome", nullable=false, length=100)
    public String getWamNome() {
        return this.wamNome;
    }
    
    public void setWamNome(String wamNome) {
        this.wamNome = wamNome;
    }

    
    @Column(name="wam_apelido", length=50)
    public String getWamApelido() {
        return this.wamApelido;
    }
    
    public void setWamApelido(String wamApelido) {
        this.wamApelido = wamApelido;
    }

    
    @Column(name="wam_cpf", unique=true, nullable=false, length=14)
    public String getWamCpf() {
        return this.wamCpf;
    }
    
    public void setWamCpf(String wamCpf) {
        this.wamCpf = wamCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="wam_dataNascimento", length=10)
    public Date getWamDataNascimento() {
        return this.wamDataNascimento;
    }
    
    public void setWamDataNascimento(Date wamDataNascimento) {
        this.wamDataNascimento = wamDataNascimento;
    }

    
    @Column(name="wam_nivel")
    public Integer getWamNivel() {
        return this.wamNivel;
    }
    
    public void setWamNivel(Integer wamNivel) {
        this.wamNivel = wamNivel;
    }

    
    @Column(name="wam_ativo")
    public Boolean getWamAtivo() {
        return this.wamAtivo;
    }
    
    public void setWamAtivo(Boolean wamAtivo) {
        this.wamAtivo = wamAtivo;
    }




}


