package bean;
// Generated 10/10/2025 15:04:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WamVendaProduto generated by hbm2java
 */
@Entity
@Table(name="wam_Venda_Produto"
    ,catalog="db_willian_martinez"
)
public class WamVendaProduto  implements java.io.Serializable {


     private Integer wamIdVendaProduto;
     private WamProduto wamProduto;
     private WamVenda wamVenda;
     private int wamQuantidade;
     private BigDecimal wamValorUnitario;

    public WamVendaProduto() {
    }

    public WamVendaProduto(WamProduto wamProduto, WamVenda wamVenda, int wamQuantidade, BigDecimal wamValorUnitario) {
       this.wamProduto = wamProduto;
       this.wamVenda = wamVenda;
       this.wamQuantidade = wamQuantidade;
       this.wamValorUnitario = wamValorUnitario;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="wam_idVendaProduto", unique=true, nullable=false)
    public Integer getWamIdVendaProduto() {
        return this.wamIdVendaProduto;
    }
    
    public void setWamIdVendaProduto(Integer wamIdVendaProduto) {
        this.wamIdVendaProduto = wamIdVendaProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="wam_idProduto", nullable=false)
    public WamProduto getWamProduto() {
        return this.wamProduto;
    }
    
    public void setWamProduto(WamProduto wamProduto) {
        this.wamProduto = wamProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="wam_idVenda", nullable=false)
    public WamVenda getWamVenda() {
        return this.wamVenda;
    }
    
    public void setWamVenda(WamVenda wamVenda) {
        this.wamVenda = wamVenda;
    }

    
    @Column(name="wam_quantidade", nullable=false)
    public int getWamQuantidade() {
        return this.wamQuantidade;
    }
    
    public void setWamQuantidade(int wamQuantidade) {
        this.wamQuantidade = wamQuantidade;
    }

    
    @Column(name="wam_valorUnitario", nullable=false, precision=10)
    public BigDecimal getWamValorUnitario() {
        return this.wamValorUnitario;
    }
    
    public void setWamValorUnitario(BigDecimal wamValorUnitario) {
        this.wamValorUnitario = wamValorUnitario;
    }




}


