package bean;
// Generated 11/10/2025 18:12:54 by Hibernate Tools 4.3.1


import java.lang.Double;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * WamVendedor generated by hbm2java
 */
@Entity
@Table(name="wam_vendedor"
    ,catalog="db_willian_martinez"
    , uniqueConstraints = @UniqueConstraint(columnNames="wam_cpf") 
)
public class WamVendedor  implements java.io.Serializable {


     private Integer wamIdVendedor;
     private String wamNome;
     private String wamCpf;
     private Date wamDataNascimento;
     private String wamTelefone;
     private Double wamComissao;
     private String wamNumero;
    // private Set wamVendas = new HashSet(0);

    public WamVendedor() {
    }

	
    public WamVendedor(String wamNome, String wamCpf) {
        this.wamNome = wamNome;
        this.wamCpf = wamCpf;
    }
    public WamVendedor(String wamNome, String wamCpf, Date wamDataNascimento, String wamTelefone, Double wamComissao, String wamNumero, Set wamVendas) {
       this.wamNome = wamNome;
       this.wamCpf = wamCpf;
       this.wamDataNascimento = wamDataNascimento;
       this.wamTelefone = wamTelefone;
       this.wamComissao = wamComissao;
       this.wamNumero = wamNumero;
       //this.wamVendas = wamVendas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="wam_idVendedor", unique=true, nullable=false)
    public Integer getWamIdVendedor() {
        return this.wamIdVendedor;
    }
    
    public void setWamIdVendedor(Integer wamIdVendedor) {
        this.wamIdVendedor = wamIdVendedor;
    }

    
    @Column(name="wam_nome", nullable=false, length=100)
    public String getWamNome() {
        return this.wamNome;
    }
    
    public void setWamNome(String wamNome) {
        this.wamNome = wamNome;
    }

    
    @Column(name="wam_cpf", unique=true, nullable=false, length=11)
    public String getWamCpf() {
        return this.wamCpf;
    }
    
    public void setWamCpf(String wamCpf) {
        this.wamCpf = wamCpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="wam_dataNascimento", length=10)
    public Date getWamDataNascimento() {
        return this.wamDataNascimento;
    }
    
    public void setWamDataNascimento(Date wamDataNascimento) {
        this.wamDataNascimento = wamDataNascimento;
    }

    
    @Column(name="wam_telefone", length=20)
    public String getWamTelefone() {
        return this.wamTelefone;
    }
    
    public void setWamTelefone(String wamTelefone) {
        this.wamTelefone = wamTelefone;
    }

    
    @Column(name="wam_comissao", precision=5)
    public Double getWamComissao() {
        return this.wamComissao;
    }
    
    public void setWamComissao(Double wamComissao) {
        this.wamComissao = wamComissao;
    }

    
    @Column(name="wam_numero", length=20)
    public String getWamNumero() {
        return this.wamNumero;
    }
    
    public void setWamNumero(String wamNumero) {
        this.wamNumero = wamNumero;
    }

//@OneToMany(fetch=FetchType.LAZY, mappedBy="wamVendedor")
//    public Set getWamVendas() {
//        return this.wamVendas;
//    }
//    
//    public void setWamVendas(Set wamVendas) {
//        this.wamVendas = wamVendas;
//    }




}


