package bean;
// Generated 10/10/2025 15:04:07 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WamVenda generated by hbm2java
 */
@Entity
@Table(name="wam_venda"
    ,catalog="db_willian_martinez"
)
public class WamVenda  implements java.io.Serializable {


     private Integer idVenda;
     private WamCliente wamCliente;
     private WamVendedor wamVendedor;
     private BigDecimal wamValor;
     private BigDecimal wamDesconto;
     private BigDecimal wamValorFinal;
     private Date dataVenda;
     private Set wamVendaProdutos = new HashSet(0);

    public WamVenda() {
    }

	
    public WamVenda(WamCliente wamCliente, WamVendedor wamVendedor, BigDecimal wamValor, BigDecimal wamDesconto, BigDecimal wamValorFinal, Date dataVenda) {
        this.wamCliente = wamCliente;
        this.wamVendedor = wamVendedor;
        this.wamValor = wamValor;
        this.wamDesconto = wamDesconto;
        this.wamValorFinal = wamValorFinal;
        this.dataVenda = dataVenda;
    }
    public WamVenda(WamCliente wamCliente, WamVendedor wamVendedor, BigDecimal wamValor, BigDecimal wamDesconto, BigDecimal wamValorFinal, Date dataVenda, Set wamVendaProdutos) {
       this.wamCliente = wamCliente;
       this.wamVendedor = wamVendedor;
       this.wamValor = wamValor;
       this.wamDesconto = wamDesconto;
       this.wamValorFinal = wamValorFinal;
       this.dataVenda = dataVenda;
       this.wamVendaProdutos = wamVendaProdutos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idVenda", unique=true, nullable=false)
    public Integer getIdVenda() {
        return this.idVenda;
    }
    
    public void setIdVenda(Integer idVenda) {
        this.idVenda = idVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCliente", nullable=false)
    public WamCliente getWamCliente() {
        return this.wamCliente;
    }
    
    public void setWamCliente(WamCliente wamCliente) {
        this.wamCliente = wamCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idVendedor", nullable=false)
    public WamVendedor getWamVendedor() {
        return this.wamVendedor;
    }
    
    public void setWamVendedor(WamVendedor wamVendedor) {
        this.wamVendedor = wamVendedor;
    }

    
    @Column(name="wam_valor", nullable=false, precision=4)
    public BigDecimal getWamValor() {
        return this.wamValor;
    }
    
    public void setWamValor(BigDecimal wamValor) {
        this.wamValor = wamValor;
    }

    
    @Column(name="wam_desconto", nullable=false, precision=4)
    public BigDecimal getWamDesconto() {
        return this.wamDesconto;
    }
    
    public void setWamDesconto(BigDecimal wamDesconto) {
        this.wamDesconto = wamDesconto;
    }

    
    @Column(name="wam_valorFinal", nullable=false, precision=4)
    public BigDecimal getWamValorFinal() {
        return this.wamValorFinal;
    }
    
    public void setWamValorFinal(BigDecimal wamValorFinal) {
        this.wamValorFinal = wamValorFinal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataVenda", nullable=false, length=10)
    public Date getDataVenda() {
        return this.dataVenda;
    }
    
    public void setDataVenda(Date dataVenda) {
        this.dataVenda = dataVenda;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="wamVenda")
    public Set getWamVendaProdutos() {
        return this.wamVendaProdutos;
    }
    
    public void setWamVendaProdutos(Set wamVendaProdutos) {
        this.wamVendaProdutos = wamVendaProdutos;
    }




}


