package bean;
// Generated 11/10/2025 18:12:54 by Hibernate Tools 4.3.1


import java.lang.Double;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WamVenda generated by hbm2java
 */
@Entity
@Table(name="wam_venda"
    ,catalog="db_willian_martinez"
)
public class WamVenda  implements java.io.Serializable {


     private Integer idVenda;
     private WamCliente wamCliente;
     private WamVendedor wamVendedor;
     private Double wamValor;
     private Double wamDesconto;
     private Double wamValorFinal;
     private Date wamDataVenda;
     

    public WamVenda() {
    }

	
    public WamVenda(WamCliente wamCliente, WamVendedor wamVendedor, Double wamValor, Double wamDesconto, Double wamValorFinal, Date dataVenda) {
        this.wamCliente = wamCliente;
        this.wamVendedor = wamVendedor;
        this.wamValor = wamValor;
        this.wamDesconto = wamDesconto;
        this.wamValorFinal = wamValorFinal;
        this.wamDataVenda = dataVenda;
    }
    public WamVenda(WamCliente wamCliente, WamVendedor wamVendedor, Double wamValor, Double wamDesconto, Double wamValorFinal, Date wamDataVenda, Set wamVendaProdutos) {
       this.wamCliente = wamCliente;
       this.wamVendedor = wamVendedor;
       this.wamValor = wamValor;
       this.wamDesconto = wamDesconto;
       this.wamValorFinal = wamValorFinal;
       this.wamDataVenda = wamDataVenda;
      
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idVenda", unique=true, nullable=false)
    public Integer getIdVenda() {
        return this.idVenda;
    }
    
    public void setIdVenda(Integer idVenda) {
        this.idVenda = idVenda;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idCliente", nullable=false)
    public WamCliente getWamCliente() {
        return this.wamCliente;
    }
    
    public void setWamCliente(WamCliente wamCliente) {
        this.wamCliente = wamCliente;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idVendedor", nullable=false)
    public WamVendedor getWamVendedor() {
        return this.wamVendedor;
    }
    
    public void setWamVendedor(WamVendedor wamVendedor) {
        this.wamVendedor = wamVendedor;
    }

    
    @Column(name="wam_valor", nullable=false, precision=4)
    public Double getWamValor() {
        return this.wamValor;
    }
    
    public void setWamValor(Double wamValor) {
        this.wamValor = wamValor;
    }

    
    @Column(name="wam_desconto", nullable=false, precision=4)
    public Double getWamDesconto() {
        return this.wamDesconto;
    }
    
    public void setWamDesconto(Double wamDesconto) {
        this.wamDesconto = wamDesconto;
    }

    
    @Column(name="wam_valorFinal", nullable=false, precision=4)
    public Double getWamValorFinal() {
        return this.wamValorFinal;
    }
    
    public void setWamValorFinal(Double wamValorFinal) {
        this.wamValorFinal = wamValorFinal;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataVenda", nullable=false, length=10)
    public Date getDataVenda() {
        return this.wamDataVenda;
    }
    
    public void setDataVenda(Date dataVenda) {
        this.wamDataVenda = dataVenda;
    }






}


